#!/bin/bash

# Author: Tushar Dimri
# Date Created: 18/07/2022
# Last Modified: 18/07/2022

# Description:
# This script backup all the files in your home directory and save them all in a .tar archive.


# Usage:
# ./backup_script

echo "Working..."

tar -cvf ~/Bash-Scripting-1/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

echo "Done."

exit 0
